title: Sách tin sinh tiếng Việt
author: Tin sinh học Việt Nam
logo: figures/TSVN.png #add your own logo here

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/favicon.png"
  baseurl :  "https://tinsinhvn.github.io/" #Replace this with your own URL

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://github.com/tinsinhvn/tinsinhvn.github.io" #add your own repo URL here
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
    bibtex_reference_style: author_year
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter

bibtex_bibfiles: 
  - content/Chap_6/Quality_control.bib
